### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by elichad** [stfc/rucio#8]
Update cookies to use RSE IDs, not names. 

Check if VO needs to be added where accounts are saved into cookies.

**Comment by patrick-austin** [comment]
Cannot find any instance of cookies relating to RSE IDs or names either in the current codebase or as a closed mainline issue. Maybe this meant cache rather than cookies, as caching against RSE name not ID was an issue (#56)?
Cookies do seem to be used when it comes to authenticating tokens at the Web layer, with the majority of references being in [WebUI utils](https://github.com/stfc/rucio/blob/master/lib/rucio/web/ui/common/utils.py). This relates to issues #10 and #25.

**Comment by elichad** [comment]
It's entirely possible that I mistook the cache for cookies - for a while I thought they overlapped but now I know they don't. If the cookies are just involved in storing auth tokens, I think we can close this.

**Comment by elichad** [comment]
I misunderstood Patrick's earlier comment - some changes are needed to incorporate the VO where account names are saved into cookies during authentication.

**Comment by patrick-austin** [comment]
Closed by mainline PR [3886](https://github.com/rucio/rucio/pull/3886).
